# Generated by Django 5.1 on 2024-10-04 21:08

import django.core.validators
import django.db.models.deletion
import sommelier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('image', models.ImageField(blank=True, upload_to=sommelier.models.upload_to)),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(choices=[('S', 'Słodkie'), ('PS', 'Półsłodkie'), ('PW', 'Półwytrawne'), ('W', 'Wytrawne')], max_length=2)),
                ('kind', models.CharField(choices=[('R', 'Czerwone'), ('B', 'Białe'), ('P', 'Różowe'), ('M', 'Musujące')], max_length=1)),
                ('country', models.CharField(choices=[('AR', 'Argentyna'), ('AU', 'Australia'), ('AT', 'Austria'), ('CL', 'Chile'), ('HR', 'Chorwacja'), ('FR', 'Francja'), ('GE', 'Gruzja'), ('ES', 'Hiszpania'), ('CA', 'Kanada'), ('MD', 'Mołdawia'), ('DE', 'Niemcy'), ('NZ', 'Nowa Zelandia'), ('PL', 'Polska'), ('PT', 'Portugalia'), ('ZA', 'RPA'), ('RO', 'Rumunia'), ('SI', 'Słowenia'), ('US', 'USA'), ('HU', 'Węgry'), ('IT', 'Włochy')], max_length=2)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(choices=[('Aldi', 'Aldi'), ('Auchan', 'Auchan'), ('Biedronka', 'Biedronka'), ('Carrefour', 'Carrefour'), ('Dino', 'Dino'), ('E.Leclerc', 'Eleclerc'), ('Groszek', 'Groszek'), ('Intermarche', 'Intermarche'), ('Kaufland', 'Kaufland'), ('Lidl', 'Lidl'), ('Społem', 'Spolem'), ('Stokrotka', 'Stokrotka'), ('Żabka', 'Zabka'), ('Inny', 'Other')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_info', to='sommelier.bottle')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='bottle',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sommelier.wine'),
        ),
    ]
