# Generated by Django 5.1 on 2024-10-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sommelier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottle',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ['-id']},
        ),
    ]
