# Generated by Django 5.1 on 2024-09-18 18:12

import sommelier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sommelier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='image',
            field=models.ImageField(blank=True, upload_to=sommelier.models.save_to),
        ),
        migrations.AlterField(
            model_name='wine',
            name='kind',
            field=models.CharField(choices=[('R', 'Czerwone'), ('B', 'Białe'), ('P', 'Różowe'), ('M', 'Musujące')], max_length=1),
        ),
        migrations.AlterField(
            model_name='wine',
            name='taste',
            field=models.CharField(choices=[('S', 'Słodkie'), ('PS', 'Półsłodkie'), ('PW', 'Półwytrawne'), ('W', 'Wytrawne')], max_length=2),
        ),
    ]
