# Generated by Django 5.1 on 2024-10-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sommelier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottles', to='sommelier.wine'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_infos', to='sommelier.bottle'),
        ),
    ]
