# Generated by Django 5.1 on 2024-10-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sommelier', '0002_alter_bottle_wine_alter_shopinfo_bottle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottle',
            options={'get_latest_by': ['-id'], 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'get_latest_by': ['-id'], 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='wine',
            options={'get_latest_by': ['-id'], 'ordering': ['-id']},
        ),
    ]
