# Generated by Django 5.1 on 2024-10-20 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sommelier', '0003_alter_bottle_options_alter_shopinfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(choices=[('Al', 'Aldi'), ('Au', 'Auchan'), ('Bi', 'Biedronka'), ('Ca', 'Carrefour'), ('DC', 'Delikatesy Centrum'), ('Di', 'Dino'), ('El', 'E.Leclerc'), ('Gr', 'Groszek'), ('In', 'Intermarche'), ('Ka', 'Kaufland'), ('Le', 'Lewiatan'), ('Li', 'Lidl'), ('Ma', 'Makro'), ('Se', 'Selgros'), ('Sp', 'Społem'), ('St', 'Stokrotka'), ('TM', 'Top Market'), ('Za', 'Żabka'), ('Ot', 'Inny')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('date', models.DateField()),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='sommelier.bottle')),
            ],
            options={
                'ordering': ['-id'],
                'get_latest_by': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='ShopInfo',
        ),
    ]
